cargo spent hours:
1 + 1 + 2 + 1 + 1 + 2 + 1.5 + 1.5 + 2

ssh dev@65.108.60.57   
ssh-copy-id dev@65.108.60.57 

add submodule:
git submodule add git@github.com:Doszhan-M/cargo.git ./cargo_app/cargo


delete submodule:
git rm -r cargo_app/cargo
rm -rf .git/modules/cargo_app/cargo


docker exec -it cargo_docker_cargo_1 bash 

python3 manage.py makemigrations
python3 manage.py migrate


python3 manage.py createsuperuser
admin_test
admin@cargo.com
testadmin2022


python manage.py migrate --fake access_protection zero
python manage.py migrate --fake-initial

sudo systemctl restart cargo 
sudo systemctl restart cargo_celery_default 
sudo systemctl restart notifier 

python manage.py collectstatic



После git pull необходимо выполнить команды:
python manage.py migrate --fake access_protection zero
python manage.py migrate --fake-initial
python manage.py collectstatic

В приложении access_protection в миграциях были ошибки, 
из-за чего проект не запускался на тестовой базе локально. То ли
проект строился поверх готовой базы, не знаю, но в миграциях некоторые 
записи ссылаются на уже имеющиеся таблицы, хотя они еще не успели создаться.
Поэтому я перекомпилировал старые миграции в новый 0001_initial. Фактически 
эта миграция никаких изменении не вносит в базу, но в базе в таблицу 
django_migrations надо  внести изменения о том, что порядок миграции изменился. 
Первые 2 команды занимаются этим и применят новые миграции. 
3 команда обновляет статику.

